services:
  digital_ustad_academy:
    ports:
      - "5000:5000"
    container_name: digital_ustad_academy_api
    restart: unless-stopped
    build:
      context: .
      target: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.digitalustad.rule=Host(`api.digitalustadacademy.com`)"
      - "traefik.http.services.digitalustad.loadbalancer.server.port=5000"
      - "traefik.http.routers.digitalustad.entrypoints=websecure"
      - "traefik.http.routers.digitalustad.tls=true"
      - "traefik.http.routers.digitalustad.tls.certresolver=letsencrypt" # for testing ssl in local type `selfsigned`  or `letsencrypt`
    networks:
      - traefik-network
    depends_on:
      - mongo
    env_file:
      - ./.env

  traefik:
    image: traefik:v3.6
    container_name: traefik-app
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=600s"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=600s"
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=600s"
      - "--entrypoints.websecure.transport.respondingTimeouts.idleTimeout=600s"
      - "--serversTransport.forwardingTimeouts.dialTimeout=30s"
      - "--serversTransport.forwardingTimeouts.responseHeaderTimeout=600s"
      - "--serversTransport.forwardingTimeouts.idleConnTimeout=600s"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=contact@digitalustadacademy.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # selef certificate
      # - "--certificatesresolvers.selfsigned.acme.tlschallenge=true"
      # - "--certificatesresolvers.selfsigned.acme.email=you@example.com"
      # - "--certificatesresolvers.selfsigned.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_letsencrypt:/letsencrypt
    networks:
      - traefik-network
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - traefik-network
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /root/mongo-data-bind-backup:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    networks:
      - traefik-network
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: ${ME_CONFIG_BASICAUTH_ENABLED}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

networks:
  traefik-network:
    external: true

volumes:
  mongo_data:
  traefik_letsencrypt:
